runtime: nodejs14

# env_variables:
#   MEMCACHE_URL: "192.168.208.3:11211"

# instance_class: F1
# automatic_scaling:
#   min_idle_instances: automatic
#   max_idle_instances: 1
#   max_instances: 1

instance_class: B2
basic_scaling:
 max_instances: 1
 idle_timeout: 30m

handlers:
- url: /css
  static_dir: webapp/dist/css
- url: /img
  static_dir: webapp/dist/img
- url: /js
  static_dir: webapp/dist/js